version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - ./pg_data:/var/lib/postgresql/data
